Add Exchange Rate repository
hmrc/forex-rates pull request #3
Opened 2022-02-02 16:51 UTC by warrenskiwork1979

2022-02-02 16:59 UTC, DevAndyroo requested changes

2022-02-02 16:59 UTC, DevAndyroo commented on test/repositories/ForexRepositorySpec.scala
> +class ForexRepositorySpec
Shouldn't this be an integration test?

2022-02-03 10:12 UTC, warrenskiwork1979 commented on test/repositories/ForexRepositorySpec.scala
> +class ForexRepositorySpec
Moved to new it directory.

2022-02-03 11:03 UTC, DevAndyroo approved these changes

2022-02-03 11:04 UTC, merged